<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="Events\**" />
    <Compile Remove="Exceptions\**" />
    <Compile Remove="Rules\**" />
    <Compile Remove="ValueObjects\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Events\**" />
    <Content Remove="Exceptions\**" />
    <Content Remove="Rules\**" />
    <Content Remove="ValueObjects\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Events\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <EmbeddedResource Remove="Rules\**" />
    <EmbeddedResource Remove="ValueObjects\**" />
    <None Remove="Controllers\**" />
    <None Remove="Events\**" />
    <None Remove="Exceptions\**" />
    <None Remove="Rules\**" />
    <None Remove="ValueObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

</Project>
